run:
  address: localhost:8080

database:
  uri: "postgresql://postgres:postgres@localhost:5432/gopher_mart_db"

migration:
  uri: "postgresql://postgres:postgres@localhost:5432/gopher_mart_db?sslmode=disable"
  dir: "internal/gophermart/migrations"

accrual:
  system:
    address: "localhost:8081"